version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.main
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: appdb
      JWT_SECRET_KEY: change-me
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
